import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { useSelector, useDispatch } from "react-redux";
import { userSelector } from "../store/user/userSelector";
import { example, exampleAction } from "../store/user/userSlice";

import NavBar from "../components/Navigation/NavBar";

const Home: NextPage = () => {
  const { valueExample } = useSelector(userSelector); //stateket nyeri ki
  const dispatch = useDispatch(); //dispatch metodus inicializalasa, actionoket kuldi el a storenak
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", flexDirection: "row" }}>
        <NavBar />

        <h1>Ola!</h1>

        <a onClick={() => dispatch(example())}>
          <h2>REDUX TEST {valueExample}</h2>
        </a>

        <a onClick={() => dispatch(exampleAction(2))}>
          <h2>REDUX TEST WITH PROP {valueExample}</h2>
        </a>
      </main>
    </div>
  );
};

export default Home;
